name: Pipeline Agenda-Bot Ruby

on:
  push:
    branches: [ main ]
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
    inputs:
      tag_name:
        description: 'Tag a desplegar a PRODUCCIÓN (ej: 1.0.0)'
        required: true

jobs:
  security-scan-job:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Gitleaks Detection
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-job:
    name: Build and Test
    needs: [security-scan-job]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.1' # Versión definida en .ruby-version
          bundler-cache: false

      - name: Install Bundler and Dependencies
        run: |
          gem install bundler -v 2.3.26
          bundle _2.3.26_ install --without staging production

      - name: Run Build Server (Linter + Tests)
        run: bundle exec rake build_server
        env:
          APP_MODE: test
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN_TEST }}

  deploy-test:
    name: Deploy to Test Environment
    needs: [ build-job ]
    runs-on: ubuntu-latest
    # CAMBIO AQUÍ: Verificamos explícitamente que sea un evento de TAG
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    environment: test
    steps:
      - name: Deploy to Render Test
        run: curl -f "${{ secrets.RENDER_DEPLOY_HOOK_TEST }}"

  deploy-production:
    name: Deploy to Production Environment
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    environment: production
    steps:
      - name: Deploy to Render Production
        run: |
          curl -f -X POST "${{ secrets.RENDER_DEPLOY_HOOK_PROD }}&ref=${{ github.event.inputs.tag_name }}"
